version: '2'

services:

  nginx-proxy:
    image: nginx:1.11
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx-proxy/etc-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-proxy/etc-nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx-proxy/etc-nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./certs:/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - nginx-proxy-log:/var/log/nginx

  node-proxy:
    image: node:6.3
    command: npm start
    environment:
      - DOCKER_SOCKET=/var/run/docker.sock
      - LOG_LEVEL=silly
      - PEOPLE_CONTAINER_IMAGE=httpd:2.4-alpine
      - PEOPLE_CONTAINER_LOG_SUFFIX=-log
      - PEOPLE_CONTAINER_PREFIX=people_apache-user-
      - PEOPLE_APACHE_CONF=$PWD/apache-user/httpd.conf
      - PORT=8080
    env_file:
      - apache-user/proxy.env
    expose:
      - "8080"
    networks:
      - proxy
    restart: always
    volumes:
      - ./node-proxy:/src:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/passwd:/etc/passwd:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - node-proxy-log:/var/log/node
    working_dir: /src

volumes:
  nginx-proxy-log:
  node-proxy-log:

networks:
  proxy:
    driver: bridge
